name: Daily R Plot

on:
  schedule:
    # Runs every day at 10 PM Eastern (which is 2 AM UTC during daylight time)
    - cron: "0 2 * * *"
  workflow_dispatch:   # lets you trigger manually from GitHub if you want

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'   # you can change this if you need a different R version

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyquant
            tidyverse
            ggplot2
            TTR
            # add any other packages your script needs

      - name: Run R script
        run: Rscript plot_script.R

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ultimate_plots/*.png || echo "No new plots to add"
          git commit -m "Daily plot update" || echo "No changes to commit"
          git push